// Project2.js
import React from 'react';

function Project2() {
    return (
        <div className="project-card">
            <h3>Senior Design</h3>
            <p>
                Designed a mobile application to aid stroke patients and at-risk individuals. In our four-person team I was tasked with developing the mobile application.
                The application allowed the user to log in using an existing account, or create a new account using an email and password.
                After logging in the user was tasked with answering a survey through the app to collect more information.
                The application also collected data from the phone sensors while the user was completing prompted tasks. This data was used in conjunction with the survey data to assess
                a fall risk. This fall risk was generated by sending all the collected data to a server and sending the server information to a MATLAB server. The MATLAB server ran a
                script to analyze the data collected. Upon generating the fall risk, the patient/user of the application was sent an email about their fall risk.
            </p>
            <a href="https://github.com/RIT-MSD-P21015" target="_blank" rel="noopener noreferrer">
                View Project on GitHub
            </a>
        </div>
    );
}

export default Project2;
